apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: guestbook
          image: kljagadish/guestbook:latest
          env:
            - name: ENV
              value: "dev"

