apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jagadishkl/applications.git'
    targetRevision: HEAD
    path: apps/guestbook/base
  destination:
    server: 'https://192.168.56.20:6443'
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

