apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
  namespace: platform-demo
  labels:
    app: guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: kljagadish/applications:latest  # Replace with your Docker Hub repo/image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook
  namespace: platform-demo
spec:
  selector:
    app: guestbook
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # Or ClusterIP/NodePort based on your environment

