name: Build and Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Git SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:$GIT_SHA .
          docker push $REGISTRY/$IMAGE_NAME:$GIT_SHA
        env:
          REGISTRY: docker.io/kljagadish
          IMAGE_NAME: guestbook

      - name: Update Kubernetes manifests with new image tag
        run: |
          sed -i "s|image:.*guestbook:.*|image: docker.io/kljagadish/guestbook:$GIT_SHA|g" ./apps/guestbook/base/deployment.yaml

      - name: Commit updated manifests
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ./apps/guestbook/base/deployment.yaml
          git commit -m "Update image tag to $GIT_SHA" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
